[Models,Tests]: Added Series & Relationship attribute models and corresponding tests.
bookbrainz/bookbrainz-data-js pull request #272
Opened 2021-05-21 16:18 UTC by akashgp09

### Summary
Added Models and their corresponding tests.

**Series Models :**

- Series
- SeriesData
- SeriesHeader
- SeriesRevision
- SeriesOrderingType

**Relationship Attribute Models:**

- RelationshipOrder
- RelationshipDate

2021-05-26 17:21 UTC, MonkeyDo reviewed
Some preliminary review comments. So far everything looks quite good, nice work !

As stated below I'm still a bit fuzzy on some of the core concepts of the relationship attributes, but overall this is a solid base for the continuation.

2021-05-26 17:21 UTC, MonkeyDo commented on src/models/relationship.js
> +		},
I've been doing some more research into database designs, and comparing how the MusicBrainz database schema works regarding relationship attributes.

I'm not yet at a point where I have a clear idea and a path forward, and I need to think about it some more before being sure that we can do everything we want this way (with a RelationshipAttributeOrdinal)

Sorry about the wait !
If you want to have a look with me, I'm looking at the [schema docs here](https://musicbrainz.org/doc/MusicBrainz_Database/Schema#Relationship_table_structure) as well as inspecting a sample MB database locally to try to understand how all the pieces fit together.


One crucial piece I'm currently missing are the tables that will allow us to describe which relationship_type will have which relationship attributes (for example, how do we describe that the "Work is part of Series" needs an ordinal attribute for ordering)

2021-05-26 17:21 UTC, MonkeyDo commented on test/testSeriesOrderingType.js
> +});
A good test to add here would be to create two SeriesOrderingTypes, and create a Relationship with a specific SeriesOrderingType, then save it with a change of ordering type and ensuring that after the save the relationship has the new ordering type is set

2021-06-07 14:02 UTC, akashgp09 commented
@MonkeyDo this is now ready for review :)

2021-06-10 15:11 UTC, MonkeyDo requested changes
Looking good so far ! Nice work

2021-06-10 15:11 UTC, MonkeyDo commented on src/models/relationshipType.js
> +		attribute() {
This would be more descriptive I think:
```suggestion
		attributeTypes() {
```

2021-06-10 15:11 UTC, MonkeyDo commented on test/testSeries.js
> +	orderingId: 1,
I think orderingTypeID would be more fitting, which would mean renaming the sql table to ordering_type_id

2021-06-10 15:34 UTC, akashgp09 commented on src/models/relationshipAttributeSet.js
> +		attribute() {
I don't know why but naming it as `attributes` gives **Error: attributes is not defined on the model**. So I had to use **attribute** instead.

2021-06-11 03:41 UTC, akashgp09 commented on src/func/types.ts
> +export interface FormRelationshipAttributesT {
Yes we can remove the type defined in set.ts and instead use this one there.

2021-06-11 15:19 UTC, MonkeyDo commented on src/models/relationshipAttributeSet.js
> +		attribute() {
Yeah, I investigated a bit, that's unfortunate but I think we can't use attributes.
I still think we should try for something else plural, it's confusing otherwise.
Maybe `relationshipAttributes` ?

2021-06-11 15:45 UTC, akashgp09 commented on src/models/relationshipAttributeSet.js
> +		attribute() {
sounds good to me :+1:

2021-06-22 17:02 UTC, MonkeyDo requested changes
Great job, everything works as expected, the tests are passing and I only have a coupl eof tiny requests below before merging

2021-06-23 05:55 UTC, akashgp09 commented on .travis.yml
> +  - git clone --branch series-entity https://github.com/bookbrainz/bookbrainz-site.git
Thank you for creating this. This will definetly help us keep track of our work and  plan out tasks for the coming weeks :100:

2021-06-23 16:08 UTC, MonkeyDo approved these changes
:rocket: !

2021-06-23 16:09 UTC, merged